version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: typed-ast
    versions:
    - 1.4.3
  - dependency-name: aiohttp
    versions:
    - 3.7.4.post0
