language: python
python:
  - "3.6"
  - "3.7"
cache: pip
install:
  - pip install pipenv
  - pipenv install
script:
  - pipenv run pylint discordbot shared
  - pipenv run mypy --ignore-missing-imports --disallow-untyped-calls --disallow-incomplete-defs .
notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update
    on_success: never
